### ISSUE TITLE
No option to change room to rm_mainmenu_debug.

### ISSUE THREAD

**Issue by ihavenoidealol1** [KockaAdmiralac/uty-save-editor#10]
The editor doesn't allow you to change your current room to rm_mainmenu_debug, and doesn't seem to recognize files with it, defaulting to "Dark Ruins - Entrance".

**Comment by KockaAdmiralac** [comment]
Have you unchecked "Show only SAVE locations"?

**Comment by ihavenoidealol1** [comment]
I didn't even see that...

**Comment by KockaAdmiralac** [comment]
It's okay! The default state of that checkbox really should be more intuitive (unchecked if the room in your save isn't a regular save room), and I'll be tracking that under #2 as it relates to the work of synchronization between these controls. Thanks!
