### ISSUE TITLE
Necklace is missing

### ISSUE THREAD

**Issue by Jerozgen** [KockaAdmiralac/uty-save-editor#16]
There's no [Necklace](https://undertaleyellow.wiki.gg/wiki/Necklace) in the editor. It's displayed as Nothing if loaded from a file

`Save.sav`
![image](https://github.com/KockaAdmiralac/uty-save-editor/assets/17567951/5afb8cb9-b0ca-4c62-9048-996740bd687a)

`uty-save-editor.netlify.app`
![image](https://github.com/KockaAdmiralac/uty-save-editor/assets/17567951/36d689c9-d048-4a26-8160-714164cd275c)

**Comment by KockaAdmiralac** [comment]
Thanks! These should be fixed in https://github.com/KockaAdmiralac/uty-save-editor/commit/2e35360cda3726fd415d17445a7983baa8795583 now, and live in a few minutes.
