### ISSUE TITLE
I've been looking for ages but I can't figure out where the flags are, and I'm trying to get a save for the alternative neutral ending.

### ISSUE THREAD

**Issue by Temmie424** [KockaAdmiralac/uty-save-editor#19]

**Comment by KockaAdmiralac** [comment]
Hey! I have now added a Hotland/New Home section where related flags for the Ceroba battle (phase and result) can be changed:
!["Hotland/New Home" section of the save editor, with "Ceroba fight phase" and "Ceroba fight result" options.](https://github.com/KockaAdmiralac/uty-save-editor/assets/11741772/92ab3dfb-3b00-4b0f-9653-a894534f56d3)
I have also added a "Flawed Pacifist final boss" save as a template save that you can start editing from, or just download. If you just want to experience the Flawed Pacifist ending, you can now pick that option:
![A "Flawed Pacifist final boss" option in the "Load a template save" modal.](https://github.com/KockaAdmiralac/uty-save-editor/assets/11741772/82b08662-d681-4b06-83aa-cb92b9fa7f2e)
The related flags are under `[HotlandFlags]`, specifically flags 2 and 3. I have also updated [the wiki page](https://undertaleyellow.wiki.gg/wiki/User:FrostTheFrozenFox/Flags#Hotland_flags) to fix this information.

Does this answer your question?

**Comment by Temmie424** [comment]
This is flawed pacifist, I'm talking about the alternative neutral, where
you've done neutral 6 times that flowey has different dialogue before and
after the fight.

**Comment by KockaAdmiralac** [comment]
Ah, I see, didn't understand what you meant. The number that stores how many times you fought Flowey is in Save02.sav, and [the editor for that file](https://save.yellow.undertale.wiki/save02) should have a number field you can use to change it. Does this work for you?

**Comment by Temmie424** [comment]
Yes it helps, thanks!

**Comment by KockaAdmiralac** [comment]
Since this is now resolved, I am closing the issue.
