### ISSUE TITLE
loading save onto the site

### ISSUE THREAD

**Issue by 12345654323456434567** [KockaAdmiralac/uty-save-editor#20]
when i try to load my save file it keeps giveing me an error idk how to replecate but it happens when i save at dunes - tree it gives this error: INI parse error: Unknown GM value type 5. thats all ik rlly

**Comment by 12345654323456434567** [comment]
ops wrong spot sorry

**Comment by KockaAdmiralac** [comment]
I'll close this in favor of #21.
